version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Navigating to the actual app folder..."
      # This path must match your GitHub folder structure exactly
      - cd 07-CICD-Pipeline-to-Deploy-Node.js-Application/node-ci-cd-app
      - npm install

  build:
    commands:
      - echo "Build started"
      - npm run build --if-present

artifacts:
  # This ensures the Deploy stage gets the files from the right folder
  base-directory: 07-CICD-Pipeline-to-Deploy-Node.js-Application/node-ci-cd-app
  files:
    - '**/*'
