version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd 07-CICD-Pipeline-to-Deploy-Node.js-Application
      - npm install

artifacts:
  base-directory: 07-CICD-Pipeline-to-Deploy-Node.js-Application
  files:
    - '**/*'
